-- CreateTable
CREATE TABLE "notaCorte" (
    "id" SERIAL NOT NULL,
    "AnoSISU" TEXT NOT NULL,
    "CodigoSISU" INTEGER NOT NULL,
    "CodigoIES" INTEGER NOT NULL,
    "Universidade" TEXT NOT NULL,
    "Nome_Estado" TEXT NOT NULL,
    "Nome_Municipio_Campus" TEXT NOT NULL,
    "Campus" TEXT NOT NULL,
    "Nome_Curso" TEXT NOT NULL,
    "Grau" TEXT NOT NULL,
    "Turno" TEXT NOT NULL,
    "Cota" TEXT NOT NULL,
    "Quant_Vagas_Cota" DOUBLE PRECISION NOT NULL,
    "Minimo_Nota_CN" DOUBLE PRECISION NOT NULL,
    "Peso_Nota_CN" DOUBLE PRECISION NOT NULL,
    "Minimo_Nota_MT" DOUBLE PRECISION NOT NULL,
    "Peso_Nota_MT" DOUBLE PRECISION NOT NULL,
    "Minimo_Nota_L" DOUBLE PRECISION NOT NULL,
    "Peso_Nota_L" DOUBLE PRECISION NOT NULL,
    "Minimo_Nota_CH" DOUBLE PRECISION NOT NULL,
    "Peso_Nota_CH" DOUBLE PRECISION NOT NULL,
    "Minimo_Nota_REDACAO" DOUBLE PRECISION NOT NULL,
    "Peso_Nota_REDACAO" DOUBLE PRECISION NOT NULL,
    "Media_Minima" DOUBLE PRECISION NOT NULL,
    "Bonus_Percentual" DOUBLE PRECISION NOT NULL,
    "Nota_Corte_1_Dia" DOUBLE PRECISION NOT NULL,
    "Diferenca_Corte_1_Para_2_Dia" DOUBLE PRECISION,
    "Nota_Corte_2_Dia" DOUBLE PRECISION,
    "Diferenca_Corte_2_Para_3_Dia" DOUBLE PRECISION,
    "Nota_Corte_3_Dia" DOUBLE PRECISION,
    "Diferenca_Corte_3_Para_4_Dia" DOUBLE PRECISION,
    "Nota_Corte_4_Dia" DOUBLE PRECISION,
    "Diferenca_Corte_4_Para_5_Dia" DOUBLE PRECISION,
    "Nota_Corte_5_Dia" DOUBLE PRECISION,
    "Diferenca_Corte_5_Para_6_Dia" DOUBLE PRECISION,
    "Nota_Corte_6_Dia" DOUBLE PRECISION,
    "Diferenca_Corte_6_Para_7_Dia" DOUBLE PRECISION,
    "Nota_Corte_7_Dia" DOUBLE PRECISION,
    "Diferenca_Corte_7_Para_8_Dia" DOUBLE PRECISION,
    "Nota_Corte_8_Dia" DOUBLE PRECISION,
    "Diferenca_Corte_8_Para_9_Dia" DOUBLE PRECISION,
    "Nota_Corte_9_Dia" DOUBLE PRECISION,

    CONSTRAINT "notaCorte_pkey" PRIMARY KEY ("id")
);
