-- CreateTable
CREATE TABLE "notaCorte" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "AnoSISU" TEXT NOT NULL,
    "CodigoSISU" INTEGER NOT NULL,
    "CodigoIES" INTEGER NOT NULL,
    "Universidade" TEXT NOT NULL,
    "Nome_Estado" TEXT NOT NULL,
    "Nome_Municipio_Campus" TEXT NOT NULL,
    "Campus" TEXT NOT NULL,
    "Nome_Curso" TEXT NOT NULL,
    "Grau" TEXT NOT NULL,
    "Turno" TEXT NOT NULL,
    "Cota" TEXT NOT NULL,
    "Quant_Vagas_Cota" REAL NOT NULL,
    "Minimo_Nota_CN" REAL NOT NULL,
    "Peso_Nota_CN" REAL NOT NULL,
    "Minimo_Nota_MT" REAL NOT NULL,
    "Peso_Nota_MT" REAL NOT NULL,
    "Minimo_Nota_L" REAL NOT NULL,
    "Peso_Nota_L" REAL NOT NULL,
    "Minimo_Nota_CH" REAL NOT NULL,
    "Peso_Nota_CH" REAL NOT NULL,
    "Minimo_Nota_REDACAO" REAL NOT NULL,
    "Peso_Nota_REDACAO" REAL NOT NULL,
    "Media_Minima" REAL NOT NULL,
    "Bonus_Percentual" REAL NOT NULL,
    "Nota_Corte_1_Dia" REAL NOT NULL,
    "Diferenca_Corte_1_Para_2_Dia" REAL,
    "Nota_Corte_2_Dia" REAL,
    "Diferenca_Corte_2_Para_3_Dia" REAL,
    "Nota_Corte_3_Dia" REAL,
    "Diferenca_Corte_3_Para_4_Dia" REAL,
    "Nota_Corte_4_Dia" REAL,
    "Diferenca_Corte_4_Para_5_Dia" REAL,
    "Nota_Corte_5_Dia" REAL,
    "Diferenca_Corte_5_Para_6_Dia" REAL,
    "Nota_Corte_6_Dia" REAL,
    "Diferenca_Corte_6_Para_7_Dia" REAL,
    "Nota_Corte_7_Dia" REAL,
    "Diferenca_Corte_7_Para_8_Dia" REAL,
    "Nota_Corte_8_Dia" REAL,
    "Diferenca_Corte_8_Para_9_Dia" REAL,
    "Nota_Corte_9_Dia" REAL
);
